update testcase

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -1,11 +1,9 @@
 workflows:
   my-workflow:
-  name: Test workflow
-    scripts:
-      - name: iOS test
-      script: | 
-        xcode-project run-tests \
-          --workspace TicTacToe.xcworkspace \
-          --scheme TicTacToe \
-          --device "iPhone 11"
-    test_report: build/ios/test/*.xml
+    scripts: 
+      - name: multi-line script
+        script: |
+          set -e # exit on first failed command
+
+          echo first command
+          echo second command
